In [6]:
import json
import os
import sys
import re
import pandas as pd

In [7]:
df = pd.read_csv('MedSynth_huggingface_final.csv')
df

,Note,Dialogue,ICD10,ICD10_desc
0,**1. Subjective:**\n\n **Chief Complaint (CC...,[doctor]: Hello! It’s good to see you today. H...,M25562,PAIN IN LEFT KNEE
1,**1. Subjective:**\n\n - **Chief Complaint (...,"[doctor] Hi there, how are you today?\n\n[pati...",M25562,PAIN IN LEFT KNEE
2,**1. Subjective:**\n\n**Chief Complaint (CC):*...,"[doctor] Good morning, how are you doing today...",M25562,PAIN IN LEFT KNEE
3,**1. Subjective:**\n\n**Chief Complaint (CC):*...,[doctor] Good morning! How are you feeling tod...,M25562,PAIN IN LEFT KNEE
4,#####\n**1. Subjective:**\n\n**Chief Complaint...,"[doctor]: Hello Mr. Doe, how are you doing tod...",M25562,PAIN IN LEFT KNEE
...,...,...,...,...
10235,#####\n**1. Subjective:**\n \n**Chief Compla...,[doctor]: Good morning. How are you doing toda...,B3781,CANDIDAL ESOPHAGITIS
10236,### Gastroenterologist Medical Note\n\n#### 1....,"**Doctor:** Hi there, how are you doing today?...",B3781,CANDIDAL ESOPHAGITIS
10237,**1. Subjective:**\n\n**Chief Complaint (CC):*...,"[doctor]: Hi Mr. Harris, how are you doing tod...",B3781,CANDIDAL ESOPHAGITIS
10238,#####\n**1. Subjective:**\n**Chief Complaint (...,"[doctor]: Good morning, Ms. Lee. How are you d...",B3781,CANDIDAL ESOPHAGITIS
10239,**1. Subjective:**\n\n**Chief Complaint (CC):*...,[doctor]: Good morning. How are you doing toda...,B3781,CANDIDAL ESOPHAGITIS

In [8]:
df = df.apply(
    lambda col: col.str.replace(r"\n{2,}", "\n", regex=True)
    if col.dtype == "object" else col
)

In [9]:
s = df["Note"].astype("string")
df["Note"] = s.apply(lambda x: x[x.find("**"):] if isinstance(x, str) and "**" in x else x)

In [10]:
datafr = df[df["Note"].str.startswith("**1. Subjective:**")]
datafr = datafr.dropna()
datafr2 = datafr[datafr["Dialogue"].str.startswith("[doctor]: ")]
df = datafr2.reset_index(drop=True)
df

,Note,Dialogue,ICD10,ICD10_desc
0,**1. Subjective:**\n **Chief Complaint (CC):...,[doctor]: Hello! It’s good to see you today. H...,M25562,PAIN IN LEFT KNEE
1,**1. Subjective:**\n**Chief Complaint (CC):** ...,"[doctor]: Hello Mr. Doe, how are you doing tod...",M25562,PAIN IN LEFT KNEE
2,**1. Subjective:**\n**CHIEF COMPLAINT:**\nSeve...,[doctor]: Good afternoon. How are you feeling ...,N390,"URINARY TRACT INFECTION, SITE NOT SPECIFIED"
3,**1. Subjective:**\n**Chief Complaint (CC):**\...,[doctor]: Good morning! How are you doing toda...,N390,"URINARY TRACT INFECTION, SITE NOT SPECIFIED"
4,**1. Subjective:**\n**Chief Complaint (CC):**\...,"[doctor]: Good morning, how are you doing toda...",N390,"URINARY TRACT INFECTION, SITE NOT SPECIFIED"
...,...,...,...,...
4262,**1. Subjective:**\n**Chief Complaint (CC):** ...,[doctor]: Good morning! How are you doing toda...,N6452,NIPPLE DISCHARGE
4263,**1. Subjective:**\n \n**Chief Complaint (CC...,[doctor]: Good morning. How are you doing toda...,B3781,CANDIDAL ESOPHAGITIS
4264,**1. Subjective:**\n**Chief Complaint (CC):**\...,"[doctor]: Hi Mr. Harris, how are you doing tod...",B3781,CANDIDAL ESOPHAGITIS
4265,**1. Subjective:**\n**Chief Complaint (CC):** ...,"[doctor]: Good morning, Ms. Lee. How are you d...",B3781,CANDIDAL ESOPHAGITIS
4266,**1. Subjective:**\n**Chief Complaint (CC):**\...,[doctor]: Good morning. How are you doing toda...,B3781,CANDIDAL ESOPHAGITIS

In [11]:
df

,Note,Dialogue,ICD10,ICD10_desc
0,**1. Subjective:**\n **Chief Complaint (CC):...,[doctor]: Hello! It’s good to see you today. H...,M25562,PAIN IN LEFT KNEE
1,**1. Subjective:**\n**Chief Complaint (CC):** ...,"[doctor]: Hello Mr. Doe, how are you doing tod...",M25562,PAIN IN LEFT KNEE
2,**1. Subjective:**\n**CHIEF COMPLAINT:**\nSeve...,[doctor]: Good afternoon. How are you feeling ...,N390,"URINARY TRACT INFECTION, SITE NOT SPECIFIED"
3,**1. Subjective:**\n**Chief Complaint (CC):**\...,[doctor]: Good morning! How are you doing toda...,N390,"URINARY TRACT INFECTION, SITE NOT SPECIFIED"
4,**1. Subjective:**\n**Chief Complaint (CC):**\...,"[doctor]: Good morning, how are you doing toda...",N390,"URINARY TRACT INFECTION, SITE NOT SPECIFIED"
...,...,...,...,...
4262,**1. Subjective:**\n**Chief Complaint (CC):** ...,[doctor]: Good morning! How are you doing toda...,N6452,NIPPLE DISCHARGE
4263,**1. Subjective:**\n \n**Chief Complaint (CC...,[doctor]: Good morning. How are you doing toda...,B3781,CANDIDAL ESOPHAGITIS
4264,**1. Subjective:**\n**Chief Complaint (CC):**\...,"[doctor]: Hi Mr. Harris, how are you doing tod...",B3781,CANDIDAL ESOPHAGITIS
4265,**1. Subjective:**\n**Chief Complaint (CC):** ...,"[doctor]: Good morning, Ms. Lee. How are you d...",B3781,CANDIDAL ESOPHAGITIS
4266,**1. Subjective:**\n**Chief Complaint (CC):**\...,[doctor]: Good morning. How are you doing toda...,B3781,CANDIDAL ESOPHAGITIS

In [ ]:
break

# TODO: Split dialogues into lists of utterances to export to JSON format

for i in range(0,len(df["Dialogue"])-1):
    df["Dialogue"][i] = list(df["Dialogue"][i].split("\n"))
df

C:\Users\Keno\AppData\Local\Temp\ipykernel_6580\1064911856.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["Dialogue"][i] = list(df["Dialogue"][i].split("\n"))

,Note,Dialogue,ICD10,ICD10_desc
0,**1. Subjective:**\n **Chief Complaint (CC):...,[[doctor]: Hello! It’s good to see you today. ...,M25562,PAIN IN LEFT KNEE
1,**1. Subjective:**\n**Chief Complaint (CC):** ...,"[[doctor]: Hello Mr. Doe, how are you doing to...",M25562,PAIN IN LEFT KNEE
2,**1. Subjective:**\n**CHIEF COMPLAINT:**\nSeve...,[[doctor]: Good afternoon. How are you feeling...,N390,"URINARY TRACT INFECTION, SITE NOT SPECIFIED"
3,**1. Subjective:**\n**Chief Complaint (CC):**\...,[[doctor]: Good morning! How are you doing tod...,N390,"URINARY TRACT INFECTION, SITE NOT SPECIFIED"
4,**1. Subjective:**\n**Chief Complaint (CC):**\...,"[[doctor]: Good morning, how are you doing tod...",N390,"URINARY TRACT INFECTION, SITE NOT SPECIFIED"
...,...,...,...,...
4262,**1. Subjective:**\n**Chief Complaint (CC):** ...,[[doctor]: Good morning! How are you doing tod...,N6452,NIPPLE DISCHARGE
4263,**1. Subjective:**\n \n**Chief Complaint (CC...,[[doctor]: Good morning. How are you doing tod...,B3781,CANDIDAL ESOPHAGITIS
4264,**1. Subjective:**\n**Chief Complaint (CC):**\...,"[[doctor]: Hi Mr. Harris, how are you doing to...",B3781,CANDIDAL ESOPHAGITIS
4265,**1. Subjective:**\n**Chief Complaint (CC):** ...,"[[doctor]: Good morning, Ms. Lee. How are you ...",B3781,CANDIDAL ESOPHAGITIS
4266,**1. Subjective:**\n**Chief Complaint (CC):**\...,[doctor]: Good morning. How are you doing toda...,B3781,CANDIDAL ESOPHAGITIS